name: record and upload
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - run: pip install yt-dlp
    - run: ffmpeg -y -loglevel verbose -headers 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.18 Safari/537.36' -headers 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -headers 'Accept-Language:en-us,en;q=0.5' -headers 'Sec-Fetch-Mode:navigate' -i https://vicparl-broadcast.akamaized.net/hls/live/2041942/pov-mob-lc/master_5500.m3u8 -c copy -f mpegts file:<(date).mp4.part
    - uses: EndBug/add-and-commit@v7
      with: 
        message: 'upload recording'
